version: "2"
services:
  node_app:
    build: .
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - mongo
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo
